### ISSUE TITLE
Not Able to access NLP slides

### ISSUE THREAD

**Issue by premchedella** [AI-Maker-Space/Awesome-AIM-Index#1]
Whenever I click on the NLP Sides, the link is pointing to https://github.com/AI-Maker-Space/Awesome-AIM-Index/tree/main instead of the slide deck.  

Could you please correct?

**Comment by chris-alexiuk** [comment]
Hello, 

Can you confirm that the slide link works as intended now?

Thanks, 
Chris

**Comment by premchedella** [comment]
Hello @chris-alexiuk,

Thank you so much.  I am able to access the slides.  

I am going to close this issue.
